const mongoose = require('./mongoose');
const Schema = mongoose.Schema;

// Normalized security-telemetry record — the single event shape every
// producer (auth routes today; eBPF/ebpf-sensor/threat-intel/risk-engine
// in later phases, per sourceSystem below) writes into. Same dual-write
// intent as GroupAuditLog.js (queryable Mongo history, additive to — not a
// replacement for — the existing pino logger.info/warn calls at each call
// site), generalized beyond groups. See SecurityEventService.js, the single
// writer of this model — routes should call that, not this model, directly.
const SecurityEventSchema = new Schema({
  // Public-safe identifier for cross-referencing this event from an API
  // response/log line without exposing the Mongo _id shape. Generated by
  // the service, not the caller — see SecurityEventService.js.
  eventId: { type: String, required: true, unique: true },

  timestamp: { type: Date, default: Date.now, required: true },

  // Free string, not a Mongoose enum — the event taxonomy (see
  // SecurityEventTypes.js) is expected to grow across future phases
  // (eBPF/network/threat-intel/risk-engine event types aren't known yet),
  // and an enum would mean a schema migration for every new type. Valid
  // values are enforced at the service layer instead (SecurityEventService
  // validates against SecurityEventTypes before writing).
  type: { type: String, required: true },

  severity: {
    type: String,
    enum: ['low', 'medium', 'high', 'critical'],
    default: 'low',
  },

  actor: {
    userId: { type: String, default: null },
    sessionId: { type: String, default: null },
  },

  source: {
    ip: { type: String, default: null },
    userAgent: { type: String, default: null },
    deviceId: { type: String, default: null },
  },

  target: {
    resource: { type: String, default: null },
    resourceId: { type: String, default: null },
    action: { type: String, default: null },
  },

  result: {
    type: String,
    enum: ['success', 'failure', 'blocked', 'unknown'],
    default: 'unknown',
  },

  // Free-form, event-type-specific detail (e.g. a rejection reason, a
  // rate-limit bucket key) — same Schema.Types.Mixed pattern
  // GroupAuditLog.metadata already uses. SecurityEventService is the
  // enforcement point for "never a secret in here", not this schema — see
  // its own comment for the exact denylist.
  metadata: { type: Schema.Types.Mixed, default: {} },

  // Correlates this event back to the originating HTTP request's pino-http
  // req.id (see init.js) — lets an operator walk
  // HTTP request -> pino log line -> this document using one shared value.
  requestId: { type: String, default: null },

  // Which subsystem produced this event. 'app' for everything in this
  // phase (routes/middleware); future phases populate 'ebpf',
  // 'network_sensor', 'threat_intelligence', 'risk_engine' etc. without any
  // schema change — this field is exactly what makes that possible (spec
  // section 22).
  sourceSystem: { type: String, default: 'app' },
});

// timestamp+type: the query-events API's default "recent events of a kind"
// listing, and severity-filtered dashboards will always add a timestamp
// range on top of this.
SecurityEventSchema.index({ timestamp: -1, type: 1 });
// actor.userId+timestamp: "show me this user's security history" — the
// single most likely admin drill-down, and a future risk-engine's primary
// lookup.
SecurityEventSchema.index({ 'actor.userId': 1, timestamp: -1 });
// source.ip+timestamp: "show me this IP's activity" — abuse investigation,
// and future threat-intel/network-anomaly correlation.
SecurityEventSchema.index({ 'source.ip': 1, timestamp: -1 });
// severity+timestamp: dashboards/alerting scanning for high/critical events
// across all types.
SecurityEventSchema.index({ severity: 1, timestamp: -1 });
// requestId: point lookups when correlating from a pino log line back to
// its event(s). Sparse — most non-security log lines never produce an
// event, so most requestId values never appear here; a non-sparse index
// would carry many entries pointing nowhere useful. (eventId's `unique`
// above already implies its own index — no separate .index() call needed.)
SecurityEventSchema.index({ requestId: 1 }, { sparse: true });

// No TTL index — security events are audit/forensic history, not ephemeral
// cache state, and nothing in the existing project requirements (CLAUDE.md,
// DECISIONS.md) calls for automatic deletion of that. Introducing one here
// would be a data-retention policy decision this Phase 1 pass has no
// authority to make silently. Revisit if/when retention requirements are
// defined explicitly.

module.exports = mongoose.model('securityEvents', SecurityEventSchema);
